num1=int(input("Enter the number1"))
num2=int(input("Enter the number2"))
print("Addition of the two numbers:",(num1+num2))
print("Subtraction of the two numbers:",(num1-num2))
print("Multiplication of the two numbers:",(num1*num2))
print("Division of the two number:",(num1/num2))
print("Remainder of the two number:",(num1%num2))